name: create_installer
on: workflow_dispatch
jobs:
  make_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install constructor and make installer
        run: $CONDA/bin/conda install constructor && $CONDA/bin/constructor Intel-AIkit/
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Intel-AIkit-2021.4.1-Linux-x86_64
          path: /home/runner/work/aikit-tests/aikit-tests/Intel-AIkit-2021.4.1-Linux-x86_64.sh
